[package]
name = "gl-client-tryout"
version = "0.1.0"
edition = "2024"

[dependencies]
gl-client = "0.3.2"
rand = "*"
bip39 = { version = "*", features=["rand_core"] }
anyhow = "1.0.100"
tokio = "1.48.0"
